[package]
name = "non-interactive-mpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
num-bigint = { version = "0.4.4", features = ["rand"] }
num-traits = "0.2.14"
